### ISSUE TITLE
Generate curated pages using yaml or json file

### ISSUE THREAD

**Issue by sammdec** [mrmrs/vimgifs#50]
For the pages like `/ex-commands`, `/getting-started` & `/motions`, instead of duplicating pages and markup, I wonder if we could use a data file with a structure something like:

``` yaml
url: "ex-commands"
title: "Ex commands"
links: 
   - title: ":!"
     url: "https://vimgifs.com/bang/"
```

or something similar?
